name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build backend
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Ensure mvnw is executable
        run: |
          git update-index --chmod=+x backend/mvnw

      - name: Convert line endings for mvnw
        run: |
          sudo apt-get install -y dos2unix
          dos2unix backend/mvnw

      - name: Build backend
        run: |
          cd backend
          ./mvnw clean install -DskipTests
  

  # Job 2: Build frontend
  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

  # Job 3: Test backend
  test-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: todoapp
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Wait for MySQL to be ready
        run: |
          sleep 15 # Počakajmo, da MySQL postane dosegljiv

      - name: Run backend tests
        run: |
          cd backend
          ./mvnw test
